travis:
  secure:
    BINSTAR_TOKEN: URyjjBS3YXMPsygndpruR/Jvy46zwjriG5ICczEkpBNZdVq2Qb1eXQ983CVYxByl4/OgLbaXPYJqp3oOIGfGqkfJzof9zdTNLXWK9lVxNWncXYF9rBWw7NzfbaFVtoKkJd0wLZ2A++hBMnJBcA5kcBdZirIs/f71t4NiDTAkv9p/DOBKbzOQzXjwgYJ2KaCsXoxWaYHFm+5DDNFbM8PkoNtvE/a1wujTDNShpauwZ8IexpPtmbj9dpvWFP4Od+GNXgQeEMh1FQ53HecJXYhsupmBFq2giYaWacUHyiaz1Lzfxy1WOFOGzuAskiYtM9Ojoya5g2UuLYfPyhFipT7ImIyZfxlsjnsXy+OQM/eD4nxMHe5BN7gxVctkptcfQVj2BiV5QYqbUiIKlZSnBGagh1U+pgZOk2kiJxz0zqzSD0q5uQvPeYHaPFHN4FezpLVzfjinveDIBIaQ9Baaget6v8ey/RoILI3etYyD+J9bBtJsPlkhFqar7E+AS39fikd03M4AuWyG3QwOwnrSlszQtijKzNA6xkodL5OmJiMAA04LmbwdOsq95EU8TbpmioExw8/fCH9PiduCgVir8ehPUkPB5JUkkIGt7hcJyICshR5NSzVxZg/XzfsBeF8q538B9UdWsZWDStxUk8dM097VR04hRndIbwrbMOfmxkip+fg=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
